#  Redis Settings
quarkus.redis.hosts=${REDIS_URL}

#Port
quarkus.http.port=${PORT:8080}
quarkus.management.enabled=true
quarkus.management.port=${MANAGEMENT_PORT:9000}

# Analytics
quarkus.analytics.disabled=true

# Logging Behavior
quarkus.log.category."io.github.eggy03.papertrail.lite".level=${APP_LOG_LEVEL:INFO}

# Native Build Args
quarkus.native.additional-build-args=\
    --trace-object-instantiation=java.security.SecureRandom,\
    --initialize-at-run-time=\
        com.neovisionaries.ws.client.Misc\\,\
        net.dv8tion.jda.internal.audio.CryptoAdapter$AbstractAaedAdapter\\,\
        net.dv8tion.jda.internal.requests.restaction.MessageCreateActionImpl

# Application Token
papertrail.general.app.discord.token=${TOKEN}

# Application Name
papertrail.general.app.name=${APP_NAME:PaperTrail Lite}

# Application Version
papertrail.general.app.version=${quarkus.application.version:N/A}

# Custom Activity
papertrail.general.app.activity=${APP_ACTIVITY:Logging Events}

# Audit Log Config
papertrail.guild.audit-log.global.log.channel=${GUILD_AUDIT_LOG_CHANNEL:-1}

## Channel Override Config
papertrail.guild.audit-log.automod.action.type.log.channel=${GUILD_AUTOMOD_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.channel.action.type.log.channel=${GUILD_CHANNEL_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.channel.override.action.type.log.channel=${GUILD_CHANNEL_OVERRIDE_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.emoji.action.type.log.channel=${GUILD_EMOJI_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.guild.update.action.type.log.channel=${GUILD_UPDATE_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.home.settings.action.type.log.channel=${GUILD_HOME_SETTINGS_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.integration.action.type.log.channel=${GUILD_INTEGRATION_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.invite.action.type.log.channel=${GUILD_INVITE_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.member.update.action.type.log.channel=${GUILD_MEMBER_UPDATE_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.message.action.type.log.channel=${GUILD_MESSAGE_ACTION_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.message.pin.action.type.log.channel=${GUILD_MESSAGE_PIN_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.mod.action.type.log.channel=${GUILD_MOD_ACTION_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.onboarding.action.type.log.channel=${GUILD_ONBOARDING_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.onboarding.prompt.action.type.log.channel=${GUILD_ONBOARDING_PROMPT_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.role.action.type.log.channel=${GUILD_ROLE_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.scheduled.event.action.type.log.channel=${GUILD_SCHEDULED_EVENT_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.soundboard.action.type.log.channel=${GUILD_SOUNDBOARD_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.stage.instance.action.type.log.channel=${GUILD_STAGE_INSTANCE_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.sticker.action.type.log.channel=${GUILD_STICKER_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.thread.action.type.log.channel=${GUILD_THREAD_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.unknown.action.type.log.channel=${GUILD_UNKNOWN_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.voice.channel.status.action.type.log.channel=${GUILD_VOICE_CHANNEL_STATUS_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.audit-log.webhook.action.type.log.channel=${GUILD_WEBHOOK_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}

papertrail.guild.boost.event.log.channel=${GUILD_BOOST_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.member.event.log.channel=${GUILD_MEMBER_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.poll.event.log.channel=${GUILD_POLL_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.security.incident.event.log.channel=${GUILD_SECURITY_INCIDENT_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}
papertrail.guild.voice.event.log.channel=${GUILD_VOICE_LOG_CHANNEL:${papertrail.guild.audit-log.global.log.channel}}

# Message Log Config
papertrail.guild.message.global.log.channel=${GUILD_MESSAGE_LOG_CHANNEL:-1}
papertrail.guild.message.retention.days=${GUILD_MESSAGE_RETENTION_DAYS:30}

# Embed Color Config
papertrail.embed-color.success.color.integer=${EMBED_COLOR_SUCCESS_COLOR_INT:712458}
papertrail.embed-color.warning.color.integer=${EMBED_COLOR_WARNING_COLOR_INT:16776960}
papertrail.embed-color.destructive.color.integer=${EMBED_COLOR_DESTRUCTIVE_COLOR_INT:16711680}