#  Redis Settings
quarkus.redis.hosts=${REDIS_URL}

#Port
quarkus.http.port=${PORT:8080}
quarkus.management.enabled=true
quarkus.management.port=${MANAGEMENT_PORT:9000}

# Analytics
quarkus.analytics.disabled=true

# Logging Behavior
quarkus.log.category."io.github.eggy03.papertrail.lite".level=${APP_LOG_LEVEL:INFO}

# Native Build Args
quarkus.native.additional-build-args=\
    --trace-object-instantiation=java.security.SecureRandom,\
    --initialize-at-run-time=\
        com.neovisionaries.ws.client.Misc\\,\
        net.dv8tion.jda.internal.audio.CryptoAdapter$AbstractAaedAdapter\\,\
        net.dv8tion.jda.internal.requests.restaction.MessageCreateActionImpl

# Application Token
papertrail.general.app.discord.token=${TOKEN}

# Application Name
papertrail.general.app.name=${APP_NAME:PaperTrail Lite}

# Application Version
papertrail.general.app.version=${quarkus.application.version:N/A}

# Custom Activity
papertrail.general.app.activity=${APP_ACTIVITY:Logging Events}

# Global Log Config
global.event.log.channel=${GLOBAL_EVENT_LOG_CHANNEL:-1}
global.message.event.log.channel=${GLOBAL_MESSAGE_EVENT_LOG_CHANNEL:-1}

## Channel Override Config
### Automod
papertrail.guild.automod-event.log.channel=${AUTOMOD_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Channel
papertrail.guild.channel-event.log.channel=${CHANNEL_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Emoji
papertrail.guild.emoji-event.log.channel=${EMOJI_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Guild Update
papertrail.guild.guild-update-event.log.channel=${GUILD_UPDATE_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Home Settings
papertrail.guild.home-settings-event.log.channel=${HOME_SETTINGS_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Integration
papertrail.guild.integration-event.log.channel=${INTEGRATION_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Invite
papertrail.guild.invite-event.log.channel=${INVITE_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Member
papertrail.guild.member-event.log.channel=${MEMBER_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### ModAction
papertrail.guild.mod-action-event.log.channel=${MOD_ACTION_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Onboarding
papertrail.guild.onboarding-event.log.channel=${ONBOARDING_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Role
papertrail.guild.role-event.log.channel=${ROLE_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Scheduled Event
papertrail.guild.scheduled-event-event.log.channel=${SCHEDULED_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Soundboard
papertrail.guild.soundboard-event.log.channel=${SOUNDBOARD_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Stage Instance
papertrail.guild.stage-instance-event.log.channel=${STAGE_INSTANCE_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Sticker
papertrail.guild.sticker-event.log.channel=${STICKER_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Thread
papertrail.guild.thread-event.log.channel=${THREAD_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Unknown
papertrail.guild.unknown-event.log.channel=${UNKNOWN_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Voice
papertrail.guild.voice-event.log.channel=${VOICE_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Webhook
papertrail.guild.webhook-event.log.channel=${WEBHOOK_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Guild Boost
papertrail.guild.boost-event.log.channel=${BOOST_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Poll
papertrail.guild.poll-event.log.channel=${POLL_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Security Incident
papertrail.guild.security-incident-event.log.channel=${SECURITY_INCIDENT_EVENT_LOG_CHANNEL:${global.event.log.channel}}
### Message
papertrail.guild.message-event.log.channel=${MESSAGE_EVENT_LOG_CHANNEL:${global.message.event.log.channel}}
papertrail.guild.message-event.retention.days=${MESSAGE_RETENTION_DAYS:30}


# Embed Color Config
papertrail.embed-color.success.color.integer=${EMBED_SUCCESS_COLOR_INT:712458}
papertrail.embed-color.warning.color.integer=${EMBED_WARNING_COLOR_INT:16776960}
papertrail.embed-color.destructive.color.integer=${EMBED_DESTRUCTIVE_COLOR_INT:16711680}