# Token
discord.token=${TOKEN}

#Port
quarkus.http.port=${PORT:8080}
quarkus.management.enabled=true
quarkus.management.port=${MANAGEMENT_PORT:9000}

# Analytics
quarkus.analytics.disabled=true
# Logging Behavior
quarkus.log.level=${LOG_LEVEL:INFO}

# Native Build Args
quarkus.native.additional-build-args=\
    --trace-object-instantiation=java.security.SecureRandom,\
    --initialize-at-run-time=\
        com.neovisionaries.ws.client.Misc\\,\
        net.dv8tion.jda.internal.audio.CryptoAdapter$AbstractAaedAdapter\\,\
        net.dv8tion.jda.internal.requests.restaction.MessageCreateActionImpl

# Project Name
project.name=${APP_NAME:PaperTrail Lite}

# Custom Activity
custom.activity=${CUSTOM_ACTIVITY:${quarkus.application.version}}

# Global Channel Config
global.audit.log.channel=${AUDIT_LOG_CHANNEL:-1}
global.message.log.channel=${MESSAGE_LOG_CHANNEL:-1}

# Channel Override Config
automod.action.log.channel=${AUTOMOD_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
channel.action.log.channel=${CHANNEL_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
channel.override.action.log.channel=${CHANNEL_OVERRIDE_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
emoji.action.log.channel=${EMOJI_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
guild.update.action.log.channel=${GUILD_UPDATE_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
home.settings.action.log.channel=${HOME_SETTINGS_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
integration.action.log.channel=${INTEGRATION_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
invite.action.log.channel=${INVITE_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
member.update.action.log.channel=${MEMBER_UPDATE_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
message.action.log.channel=${MESSAGE_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
message.pin.action.log.channel=${MESSAGE_PIN_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
mod.action.action.log.channel=${MOD_ACTION_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
onboarding.action.log.channel=${ONBOARDING_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
onboarding.prompt.action.log.channel=${ONBOARDING_PROMPT_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
role.action.log.channel=${ROLE_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
scheduled.event.action.log.channel=${SCHEDULED_EVENT_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
soundboard.action.log.channel=${SOUNDBOARD_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
stage.instance.action.log.channel=${STAGE_INSTANCE_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
sticker.action.log.channel=${STICKER_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
thread.action.log.channel=${THREAD_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
unknown.action.log.channel=${UNKNOWN_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
voice.channel.status.action.log.channel=${VOICE_CHANNEL_STATUS_ACTION_LOG_CHANNEL:${global.audit.log.channel}}
webhook.action.log.channel=${WEBHOOK_ACTION_LOG_CHANNEL:${global.audit.log.channel}}

guild.boost.event.log.channel=${GUILD_BOOST_EVENT_LOG_CHANNEL:${global.audit.log.channel}}
guild.member.event.log.channel=${GUILD_MEMBER_EVENT_LOG_CHANNEL:${global.audit.log.channel}}
guild.poll.event.log.channel=${GUILD_POLL_EVENT_LOG_CHANNEL:${global.audit.log.channel}}
guild.security.incident.event.log.channel=${GUILD_SECURITY_INCIDENT_EVENT_LOG_CHANNEL:${global.audit.log.channel}}
guild.voice.event.log.channel=${GUILD_VOICE_EVENT_LOG_CHANNEL:${global.audit.log.channel}}

# Guild Message Settings

##  Redis Settings
quarkus.redis.hosts=${REDIS_URL}

## Retention Days
guild.message.retention.days=${GUILD_MESSAGE_RETENTION_DAYS:30}